version: '3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: spring-demo
      MYSQL_DATABASE: spring-demo
      MYSQL_USER: spring-demo
      MYSQL_PASSWORD: spring-demo
    volumes:
    - /var/lib/mysql
    ports:
    - 3306:3306